CREATE TABLE admins (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(100) NOT NULL UNIQUE,
  correo VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  foto VARCHAR(255) DEFAULT NULL,
  rol ENUM('admin', 'superadmin') DEFAULT 'admin',
  fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);